import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { ApiContent, PremiumContent } from '../types.ts'

export async function writePages(dist: string, pages: Array<[string, string]>): Promise<void> {
  const distPath = fileURLToPath(new URL(dist))

  for (const [file, content] of pages) {
    const outPath = join(distPath, file)
    await mkdir(dirname(outPath), { recursive: true })
    await writeFile(outPath, content)
  }
}

export async function emitWorkerContentModule(
  src: string,
  data: { content: Record<string, ApiContent>; premium: Record<string, PremiumContent> },
): Promise<void> {
  const module = `// Generated by the blog build. Do not edit.\n` +
    `export const content = ${JSON.stringify(data.content, null, 2)}\n` +
    `export const premium = ${JSON.stringify(data.premium, null, 2)}\n`

  const workerDir = new URL('../worker/', src)
  await mkdir(workerDir, { recursive: true })
  await writeFile(new URL('content.generated.js', workerDir), module)
}
