import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { parseYaml } from '../util/utils.js'

const decoder = new TextDecoder()

/**
 * Build-time plugin: emit a Worker module (`worker/content.generated.js`) with
 * two maps, imported into the Worker bundle rather than written to `dist/`:
 *   - `content`: free posts' structured JSON for the agent API (excludes paid).
 *   - `premium`: paid posts' full rendered HTML, served only after payment.
 * Paid content is thus never exposed as a public static asset nor via the
 * cheaper agent API.
 */
export const apiContentPlugin = {
  name: 'api-content',
  /**@param {import("./core.js").Core} core  */
  apply(core) {
    core.addhook(
      'beforeBuild',
      async (/**@type {import("../util/type.js").Config} */ config) => {
        const { src } = config
        const posts = new URL('./posts/', src)

        /**@type {Record<string, object>} */
        const content = {}

        for (const entry of await readdir(posts, { withFileTypes: true })) {
          if (!entry.isFile || !entry.name.endsWith('.md')) continue

          const slug = entry.name.replace(/\.md$/, '')
          const raw = decoder.decode(
            await readFile(new URL(entry.name, posts)),
          )
          const [meta, md] = parseYaml(raw)
          if (meta.paid) continue // paid posts go in `premium`, not the API map

          const { title, date, tags, summary } = meta
          content[slug] = { slug, title, date, tags, summary, markdown: md.trim() }
        }

        // Full HTML of paid posts, rendered by the post plugin (runs first).
        const premiumPages = core.plugins.get('post').premiumPages ?? {}
        /**@type {Record<string, object>} */
        const premium = {}
        for (const [slug, page] of Object.entries(premiumPages)) {
          premium[slug] = {
            slug,
            title: page.title,
            html: page.html,
            ...(page.price ? { price: page.price } : {}),
          }
        }

        const module = `// Generated by api-content plugin. Do not edit.\n` +
          `export const content = ${JSON.stringify(content, null, 2)}\n` +
          `export const premium = ${JSON.stringify(premium, null, 2)}\n`

        const workerDir = new URL('../worker/', src)
        await mkdir(workerDir, { recursive: true })
        await writeFile(
          new URL('content.generated.js', workerDir),
          module,
        )
      },
    )
  },
}
