// Type declarations for the build artifact emitted by src/blog/emit.ts
// (emitWorkerContentModule). The .js file is gitignored and generated by
// `pnpm build`, so this file lets typecheck pass on a fresh checkout.

export declare const content: Record<string, {
  slug: string
  title: string
  date: string
  tags?: string[]
  summary?: string
  markdown: string
}>

export declare const premium: Record<string, {
  slug: string
  title: string
  html: string
  price?: string
}>
