name: Deploy to gh-pages

on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Generate dist dir
        run: |
          deno task build
      - name: deploy gh-pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
